# Storage driver
storage = "memory" # options: dummy, database, file, memory, redis

# use the follow entry for a customer driver
# note: you will need to comment out the entry above
#
# storage.custom = ""

# lifetime is in minutes
lifetime = 60

# session cookie name
cookie = "dty_session"
