[workspace]
members = [
  "bin/dirtybase",
  "bin/dirtybase-ui",
  "lib/dirtybase_db",
  "lib/dirtybase_db_macro",
  "lib/dirtybase_db_internal",
  "bin/dirtybase-tos/front",
  "bin/dirtybase-tos/app",
  "bin/dirtybase-tos/server",
  "bin/ui",
]
resolver = "2"

[[workspace.metadata.leptos]]
name = "dirtybase-tos"
bin-package = "dirtybase-tos-server"
lib-package = "dirtybase-tos-front"

# need to be applied only to wasm build
[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'


[workspace.dependencies]
actix-web = "4.3.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [
  "runtime-tokio-rustls",
  "mysql",
  "sqlite",
  "any",
  "chrono",
  "json",
] }
chrono = { version = "0.4.26", features = ["serde"] }
async-trait = "0.1.64"
pretty_env_logger = "0.5.0"
log = "0.4.17"
actix-files = "0.6.2"
bcrypt = "0.14.0"
rand = "0.8.5"
futures = "0.3.27"
futures-util = "0.3.27"
ulid = { version = "1.0.0", features = ["serde", "rand", "std"] }
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }
futures-channel = "0.3.28"
native-tls = "0.2.11"
tokio = { version = "1.27.0", features = ["sync"] }
hmac = "0.12.1"
jwt = "0.16.0"
sha2 = "0.10"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
dotenvy = "0.15"
# cookie = { version = "0.17", features= ["default", "secure-cookies"] }
#------------------------------
leptos = { version = "0.3", default-features = false, features = ["stable"] }
leptos_meta = { version = "0.3", default-features = false }
leptos_router = { version = "0.3", default-features = false, features = [
  "stable",
] }
leptos_dom = { version = "0.3", default-features = false }
leptos_actix = { version = "0.3" }
busybody = { version = "0.2.3" }
orsomafo = { version = "0.1.4" }
fama = { version = "0.2.0" }
