[workspace]
resolver = "2"
members = ["bin/ui", "bin/cli", "lib/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
axum = { version = "0.7.4" }
actix-web = "4.3.0"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
toml = "0.8.0"
sqlx = { version = "0.7.3", features = [
  "runtime-tokio",
  "tls-rustls",
  "all-databases",
  "chrono",
  "json",
] }
chrono = { version = "0.4.31", features = ["serde"] }
async-trait = "0.1.64"
pretty_env_logger = "0.5.0"
log = "0.4.17"
actix-files = "0.6.2"
bcrypt = "0.15.0"
rand = "0.8.5"
futures = "0.3.27"
futures-util = "0.3.27"
ulid = { version = "1.0.0", features = ["serde", "rand", "std"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
futures-channel = "0.3.28"
native-tls = "0.2.11"
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
tokio-util = { version = "0.7.10", features = ["full"] }
hmac = "0.12.1"
mime = "0.3.17"
jwt = "0.16.0"
sha2 = "0.10"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
dotenvy = "0.15"
# cookie = { version = "0.17", features= ["default", "secure-cookies"] }
busybody = { version = "0.3" }
orsomafo = { version = "0.3" }
fama = { version = "0.3" }
busstop = { version = "0.2" }
redis = { version = "0.25", features = [
  "tokio-comp",
  "aio",
  # "tls-native-tls",
  "cluster-async",
] }
lettre = { version = "0.11.0" }
config = "0.14"
deadpool = "0.11"
deadpool-redis = { version = "0.15" }
cron = { version = "0.12" }
validator = { version = "0.18", features = ["derive"] }
tower-service = { version = "0.3" }
named_routes_axum = { version = "0.1" }
