[workspace]
resolver = "2"
members = ["bin/ui", "bin/cli", "packages/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
axum = { version = "0.8", features = ["ws", "multipart"] }
dashmap = { version = "6" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "unstable-doc"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
sqlx = { version = "0.8", features = [
	"runtime-tokio",
	"tls-rustls",
	"all-databases",
	"chrono",
	"json",
	"macros",
] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
pretty_env_logger = "0.5"
log = "0.4"
bcrypt = "0.15"
rand = "0.8"
futures = "0.3"
futures-util = "0.3"
ulid = { version = "1.0", features = ["serde", "rand", "std"] }
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
futures-channel = "0.3"
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["full"] }
hmac = "0.12"
mime = "0.3"
jwt = "0.16"
jsonwebtoken = "9"
sha2 = "0.10"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
dotenvy = "0.15"
busybody = { version = "0.3" }
orsomafo = { version = "0.3" }
fama = { version = "0.3" }
busstop = { version = "0.2" }
redis = { version = "0.27", features = [
	"tokio-comp",
	"aio",
	# "tls-native-tls",
	"cluster-async",
] }
lettre = { version = "0.11.0" }
config = "0.14"
deadpool = "0.12"
deadpool-redis = { version = "0.18" }
cron = { version = "0.12" }
english-to-cron = { version = "0.1" }
validator = { version = "0.18", features = ["derive"] }
tower-service = { version = "0.3" }
named_routes_axum = { version = "0.2" }
simple-middleware = { version = "0.1" }
Inflector = { version = "0.11" }
axum-extra = { version = "0.10", features = [
	"form",
	"cookie",
	"cookie-private",
	"cookie-signed",
	"query",
	"protobuf",
	"typed-header",
	"async-read-body",
	"multipart",
	"file-stream",
] }
mime_guess = { version = "2.0" }
tower-http = { version = "0.6", features = ["full"] }
hex = { version = "0.4" }
utoipa = { version = "5", features = ["axum"] }
utoipa-axum = { version = "0.1" }
uuid7 = { version = "1", features = ["serde", "uuid"] }
uuid25 = { version = "0.3", features = ["gen", "serde", "uuid"] }
dirtybase_app = { version = "*" }
dirtybase_contract = { version = "*" }
dirtybase_helper = { version = "*" }
dirtybase_db = { version = "*" }
dirtybase_config = { version = "*" }
dirtybase_cache = { version = "*" }
dirtybase_mail = { version = "*" }
dirtybase_db_macro = { version = "*" }
dirtybase_user = { version = "*" }
dirtybase_auth = { version = "*" }
dirtybase_cron = { version = "*" }
dirtybase_3rd_client = { version = "*" }

[patch.crates-io]
dirtybase_contract = { path = "./packages/contract" }
dirtybase_db_macro = { path = "./packages/db_macro" }
dirtybase_3rd_client = { path = "./packages/3rd_client" }
dirtybase_app = { path = "./packages/app" }
dirtybase_helper = { path = "./packages/helper" }
dirtybase_db = { path = "./packages/db" }
dirtybase_config = { path = "./packages/config" }
dirtybase_cache = { path = "./packages/cache" }
dirtybase_mail = { path = "./packages/mail" }
dirtybase_user = { path = "./packages/user" }
dirtybase_auth = { path = "./packages/auth" }
dirtybase_cron = { path = "./packages/cron" }
