[workspace]
resolver = "2"
members = [
  "bin/dirtybase",
  "lib/dirtybase_db",
  "lib/dirtybase_db_macro",
  "lib/dirtybase_db_types",
  "bin/ui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.3.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.7.1", features = [
  "runtime-tokio",
  "tls-rustls",
  "mysql",
  "sqlite",
  "any",
  "chrono",
  "json",
] }
chrono = { version = "0.4.26", features = ["serde", "time"] }
async-trait = "0.1.64"
pretty_env_logger = "0.5.0"
log = "0.4.17"
actix-files = "0.6.2"
bcrypt = "0.15.0"
rand = "0.8.5"
futures = "0.3.27"
futures-util = "0.3.27"
ulid = { version = "1.0.0", features = ["serde", "rand", "std"] }
tokio-tungstenite = { version = "0.20.0", features = ["native-tls"] }
futures-channel = "0.3.28"
native-tls = "0.2.11"
tokio = { version = "1.27.0", features = ["sync"] }
hmac = "0.12.1"
mime = "0.3.17"
jwt = "0.16.0"
sha2 = "0.10"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
dotenvy = "0.15"
# cookie = { version = "0.17", features= ["default", "secure-cookies"] }
busybody = { version = "0.3.0" }
orsomafo = { version = "0.2.0" }
fama = { version = "0.3.1" }
redis = { version = "0.23.1", features = [
  "tokio-comp",
  "aio",
  # "tls-native-tls",
  "cluster-async",
] }
