[workspace]
resolver = "2"
members = ["bin/ui", "bin/cli", "packages/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
axum = { version = "0.7", features = ["ws", "multipart"] }
dashmap = { version = "6" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "unstable-doc"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
sqlx = { version = "0.8", features = [
	"runtime-tokio",
	"tls-rustls",
	"all-databases",
	"chrono",
	"json",
	"macros",
] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
pretty_env_logger = "0.5"
log = "0.4"
bcrypt = "0.15"
rand = "0.8"
futures = "0.3"
futures-util = "0.3"
ulid = { version = "1.0", features = ["serde", "rand", "std"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
futures-channel = "0.3"
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["full"] }
hmac = "0.12"
mime = "0.3"
jwt = "0.16"
sha2 = "0.10"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
dotenvy = "0.15"
# cookie = { version = "0.17", features= ["default", "secure-cookies"] }
busybody = { version = "0.3" }
orsomafo = { version = "0.3" }
fama = { version = "0.3" }
busstop = { version = "0.2" }
redis = { version = "0.27", features = [
	"tokio-comp",
	"aio",
	# "tls-native-tls",
	"cluster-async",
] }
lettre = { version = "0.11.0" }
config = "0.14"
deadpool = "0.12"
deadpool-redis = { version = "0.18" }
cron = { version = "0.12" }
english-to-cron = { version = "0.1" }
validator = { version = "0.18", features = ["derive"] }
tower-service = { version = "0.3" }
named_routes_axum = { version = "0.1" }
simple-middleware = { version = "0.1" }
Inflector = { version = "0.11" }
axum-extra = { version = "0.9", features = [
	"form",
	"cookie",
	"cookie-private",
	"cookie-signed",
	"query",
	"protobuf",
] }
mime_guess = { version = "2.0" }
tower-http = { version = "0.6", features = ["full"] }
hex = { version = "0.4" }
utoipa = { version = "5" }
