[package]
name = "dirtybase_db_macro"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
# dirtybase_contract = { path = "../contract", version = "*" }
dirtybase_common = { path = "../common", version = "*" }
busybody = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
sqlx = { workspace = true }
proc-macro2 = { version = "1.0.62", default-features = false }
anyhow = { workspace = true }
cruet = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
dirtybase_db = { path = "../db", version = "*" }
dirtybase_helper = { path = "../helper", version = "*" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
