[package]
name = "dirtybase_permission"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { path = "../contract", version = "*" }
dirtybase_helper = { path = "../helper", version = "*" }
dirtybase_db_macro = { path = "../db_macro", version = "*" }
serde = { workspace = true }
