[package]
name = "dirtybase_permission"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { workspace = true }
dirtybase_helper = { workspace = true }
dirtybase_db_macro = { workspace = true }
dirtybase_common = { workspace  = true }
serde = { workspace = true }
tracing = { workspace = true }


[features]
migration = []
