[package]
name = "dirtybase_auth"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_db_macro = { path = "../db_macro", version = "*" }
dirtybase_contract = { path = "../contract", version = "*" }
dirtybase_helper= { path = "../helper", version = "*" }
dirtybase_session = { path = "../session", version = "*" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
orsomafo = { workspace = true }
busybody = { workspace = true }
busstop = { workspace = true }
sha2 = { workspace = true }
log = { workspace = true }
bcrypt = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
simple-middleware = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
