[package]
name = "dirtybase_multitenant"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { workspace = true }
dirtybase_common = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
