[package]
name = "dirtybase_session"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_db_macro = { path = "../db_macro", version = "*" }
dirtybase_contract = { path = "../contract", version = "*" }
dirtybase_helper = { path = "../helper", version = "*" }
dirtybase_cron = { path = "../cron", version = "*" }
simple-middleware = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
bcrypt = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
busybody = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
uuid25 = { workspace = true }
tracing = { workspace = true }
cookie = { workspace = true }