enable = true

storage = "memory" #options: memory, database

# for a custom storage using the following.
# Note: you need to comment out the entry `storage =....`
# storage.custom = 

allow_self_signup = false
signin_form_route = "auth:signin-form"
auth_route = "auth::do-signin"
