[package]
name = "dirtybase_scribe"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { path = "../contract" }
dirtybase_config = { path = "../config" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
orsomafo = { workspace = true }
busstop = { workspace = true }
busybody = { workspace = true }
ulid = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
