[package]
name = "dirtybase_lock"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { workspace = true }
dirtybase_db_macro = { workspace = true }
dirtybase_common = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
