[package]
name = "dirtybase_cron"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_contract = { path = "../contract", version = "*" }
cron = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
busybody = { workspace = true }
busstop = { workspace = true }
english-to-cron = { workspace = true }
orsomafo = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
