enable = true

# options: domain, subdomain, header, query
id_location = "subdomain"

# option: database, dummy 
storage = "memory"

# for a custom storage driver use the following
# Note: You will need to turn off the above "storage" entry
# storage.custom=""
