# Toggle the feature
enable = true

# The database configuration set to use
# This value is used when the storage is set to 'database'
db_config_set = ""

# Header key that stores the tenant's ID
header_key = "X-Tenant-ID"

# Heaker key that stores the tenant's token value
token_header_key = "X-Tenant-Token"

# Query string used for the tenant's ID 
query_key = "tenant-id"

# Cookie key used for the tenant's ID 
cookie_key = "tenant-id"

# Query string used for the tenant's  token value
token_query_key = "tonant-tk"

# Where tenants data is store
# option: database, memory, dummy 
storage = "memory"

# If set to true, a tenant will be require before the require or command is handled
tenant_require = false
