[package]
name = "dirtybase_app"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirtybase_db = { workspace = true }
dirtybase_db_macro = { workspace = true }
dirtybase_cache = { workspace = true }
dirtybase_mail = { workspace = true }
dirtybase_contract = { workspace = true }
dirtybase_helper = { workspace = true }
dirtybase_cron = { workspace = true }
dirtybase_auth = { workspace = true }
dirtybase_permission = { workspace = true, optional = true }
dirtybase_session = { workspace = true }
dirtybase_multitenant = { workspace = true, optional = true }
dirtybase_encrypt = { workspace = true }
dirtybase_common = { workspace = true }
dirtybase_realtime = { workspace = true, optional = true }
simple-middleware = { workspace = true }
anyhow = { workspace = true }
validator = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
base64ct = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
pretty_env_logger = { workspace = true }
log = { workspace = true }
# actix-files = { workspace = true }
bcrypt = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hmac = { workspace = true }
jwt = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
busybody = { workspace = true }
orsomafo = { workspace = true }
fama = { workspace = true }
redis = { workspace = true }
mime = { workspace = true }
axum = { workspace = true }
busstop = { workspace = true }
tower-service = { workspace = true }
tower-http = { workspace = true }
named_routes_axum = { workspace = true }
axum-extra = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tera = { workspace = true, optional = true }
reqwest = { workspace = true }
serde_urlencoded = { workspace = true }


[features]
permission = ["dep:dirtybase_permission"]
multitenant = ["dep:dirtybase_multitenant", "permission"]
realtime = ["dep:dirtybase_realtime"]
template = ["dep:tera"]
embed_template = ["template"]
full = ["multitenant", "template", "realtime"]
default = ["full"]
