[package]
name = "ui"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = { version = "0.7.3" }
dirtybase_app = { path = "../../packages/app" }
log = { workspace = true }
pretty_env_logger = { workspace = true }
busybody = { workspace = true }
tokio = { workspace = true }
mime_guess = { workspace = true }
