[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = { version = "0.7.3" }
dirtybase = { path = "../dirtybase" }
actix-web = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
busybody = { workspace = true }
