# Application current mode
# Valid options: dev, prod, staging 
env = "dev"

# Application's name
name = "Dirty Base App"

# Security
key = ""
previous_keys = []

#------------------------------------------------
#       Web 
#------------------------------------------------
web_port = 8080
web_ip_address = "0.0.0.0"
web_public_directory = "./public"

#       Web 
#------------------------------------------------


#------------------------------------------------
#       Web Cookie
#------------------------------------------------
[web_cookie]
http_only = true
same_site = "lax" # options: lax, strict, none
secure = true
encrypt = true


#       Web Cookie
#------------------------------------------------


#------------------------------------------------
#       Web Route collection 
#------------------------------------------------
web_enable_general_routes = true
web_enable_admin_routes = true
web_enable_api_routes = true
web_enable_insecure_api_routes = true
web_enable_dev_routes = true

#       Web Route collection 
#------------------------------------------------

#------------------------------------------------
#       Web middleware 
#------------------------------------------------
[web_middleware]
admin_route = []
api_route = []
dev_route = []
general_route = []
global = []
insecure_api_route = []


#------------------------------------------------
#       Web CORs 
#------------------------------------------------
[web_api_routes_cors]
headers = ["*"]
methods = ["*"]
origins = ["*"]
expose = ["*"]

[web_insecure_api_routes_cors]
headers = ["*"]
methods = ["*"]
origins = ["*"]
expose = ["*"]

[web_general_routes_cors]
headers = []
methods = []
origins = []
expose = []

[web_backend_routes_cors]
headers = []
methods = []
origins = []
expose = []

[web_admin_routes_cors]
headers = []
methods = []
origins = []
expose = []

[web_dev_routes_cors]
headers = []
methods = []
origins = []
expose = []

#       Web CORS 
#------------------------------------------------

#------------------------------------------------
#      Web proxy and fowarded seaders
#------------------------------------------------
web_trusted_proxies= [] # list of IP addresses or IPNET addresses
# One or more headers to source the client's IP address from
# The order is important. Searching will stop on the first valid result
web_proxy_trusted_headers=[]

#      Web proxy and fowarded seaders
#------------------------------------------------

#------------------------------------------------
#       Web Route collection prefix
#------------------------------------------------
web_api_route_prefix = "/api"
web_insecure_api_route_prefix = "/_open"
web_admin_route_prefix = "/_admin"
web_dev_route_prefix = "/_dev"

#       Dirtybase Web Route collection prefix
#------------------------------------------------
