[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "dirtybase_cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirtybase_contract = { workspace = true }
dirtybase_helper = { workspace = true }
clap = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
