enable = false


[jobs.foo2-job] # Jobs 
enable = true
schedule = "0/10 * * * * * *"
description = "This is the description of what foo:job does...."
args = "foo, bar"                                                # A comma separated list of arguments to be passed to the job
