enable = false


# Jobs 
[jobs.foo] 
enable = true
schedule = "0/10 * * * * * *"
description = "This is the description for cron foo" 
# A comma separated list of arguments to be passed to the job
args = "arg1, arg2"  
