enable = false


[jobs.foo] # Jobs 
enable = true
schedule = "0/10 * * * * * *"
description = "This is the description for cron foo" 
args = "arg1, arg2"                                                # A comma separated list of arguments to be passed to the job
