[package]
name = "dirtybase_mail"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirtybase_config = { path = "../config" }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
async-trait = { workspace = true }
orsomafo = { workspace = true }
log = { workspace = true }
lettre = { workspace = true }
