[package]
name = "dirtybase_user"
version.workspace = true
edition.workspace = true

[dependencies]
dirtybase_db_macro = { path = "../db_macro" }
dirtybase_contract = { path = "../contract" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
orsomafo = { workspace = true }
sha2 = { workspace = true }
log = { workspace = true }
bcrypt = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
