[package]
name = "dirtybase_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["unstable-doc"] }
dirtybase_helper = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
orsomafo = { workspace = true }
validator = { workspace = true }
busstop = { workspace = true }
busybody = { workspace = true }
ulid = { workspace = true }
simple-middleware = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
crypto = { workspace = true }
argon2 = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
named_routes_axum = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
# sha2 = { workspace = true }
Inflector = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
config = { workspace = true }
base64ct = { workspace = true }
