[package]
name = "dirtybase_helper"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
Inflector = { workspace = true }
ulid = { workspace = true }
uuid = { workspace = true }
uuid25 = { workspace = true }
base64ct = { workspace = true }
hex = { workspace = true }
snowflaker = { workspace = true, features = ["dynamic"] }
