[package]
name = "dirtybase"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirtybase_db = { path = "../../lib/dirtybase_db" }
dirtybase_config = { path = "../../lib/dirtybase_config" }
dirtybase_cache = { path = "../../lib/dirtybase_cache" }
dirtybase_mail = { path = "../../lib/dirtybase_mail" }
dirtybase_contract = { path = "../../lib/dirtybase_contract" }
actix-web = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
pretty_env_logger = { workspace = true }
log = { workspace = true }
actix-files = { workspace = true }
bcrypt = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hmac = { workspace = true }
jwt = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
busybody = { workspace = true }
orsomafo = { workspace = true }
fama = { workspace = true }
redis = { workspace = true }
mime = { workspace = true }
axum = { workspace = true }
busstop = { workspace = true }
